---
output: html_document
editor_options: 
chunk_output_type: console
---
```{r}
library(tidyverse)
```

```{r}
data <- read.csv("uo_nn_batch_123456-789101.csv", sep = ";")
summary(data)
str(data)
```

```{r}
# New Column Method Name

data$Method <- "GM"
data$Method[data$isd == 3] <- "QNM"
data$Method[data$isd == 7] <- "SGM"
```

## Convergence

### Global

```{r}
# Lambda vs L*

boxplot_la_l_opt <- data %>%
    ggplot(aes(x = Method, y = L., color = factor(la))) +
    geom_boxplot() +
    geom_jitter(shape = 16, position = position_jitter(0.2)) +
    xlab("") +
    ylab("Optiaml L") +
    guides(col = guide_legend(title = "Lambda")) +
    ggtitle("L* vs Lambda") +
    theme(
        legend.title = element_text(color = "blue", size = 10),
        legend.text = element_text(color = "red"),
        plot.title = element_text(
            color = "black",
            size = 30,
            face = "bold",
            hjust = 0.5)
    )

boxplot_la_l_opt
```


```{r}
#average value of the loss function

table_d<- data %>%
  group_by(la,Method) %>% 
  summarize(mean_L = round(mean(L.),3))
table_d
```


```{r}
# Stacked Optimal L per lambda

l_opt_la_g_plot <- data %>%
    ggplot(aes(x = factor(la), y = L., fill = Method)) +
    geom_bar(stat = "identity") +
    xlab("Lambda") +
    ylab("Optimal L") +
    guides(col = guide_legend(title = "Lambda")) +
    ggtitle("Stacked Optimal L per lambda") +
    theme(
        legend.title = element_text(color = "blue", size = 10),
        legend.text = element_text(color = "red"),
        plot.title = element_text(
            color = "black",
            size = 30,
            face = "bold",
            hjust = 0.5)
    )
l_opt_la_g_plot
```




### Local

```{r}
# Time Execution per Method

tex_g_plot <- data %>%
    ggplot(aes(x = num_target, y = tex, color = Method)) +
    geom_line() +
    facet_grid(~factor(la)) +
    scale_x_continuous(breaks = seq(0, 10, by = 1)) +
    scale_y_continuous(trans = "log10") +
    ylab("Time of Execution (s)") +
    xlab("Target Number") +
    guides(col = guide_legend(title = "Method")) +
    ggtitle("Time Execution per Method") +
    theme(
        legend.title = element_text(color = "blue", size = 10),
        plot.title = element_text(
            color = "black",
            size = 30,
            face = "bold",
            hjust = 0.5)
    )
tex_g_plot
```

```{r}
# Stacked Time Execution
stck_tex_g_plot <- data %>%
    ggplot(aes(x = factor(num_target), y = niter, fill = factor(isd))) +
    geom_bar(stat = "identity") +
    scale_y_continuous(trans = "log10") +
    ylab("Time of Execution (s)") +
    xlab("Target Number") +
    guides(fill = guide_legend(title = "Method")) +
    ggtitle("Stacked Time Execution") +
    theme(
        legend.title = element_text(color = "blue", size = 10),
        plot.title = element_text(
            color = "black",
            size = 30,
            face = "bold",
            hjust = 0.5)
    ) +
    scale_fill_discrete(labels = c(unique(data$Method)))

stck_tex_g_plot
```



```{r}
# Iterations per Method for each target number

niter_g_plot <- data %>%
    ggplot(aes(x = num_target, y = niter, color = Method)) +
    geom_line() +
    scale_y_continuous(trans = "log2") +
    scale_x_continuous(breaks = seq(0, 10, by = 1)) +
    facet_grid(~factor(la)) +
    ylab("Number of Iteration") +
    xlab("Target Number") +
    guides(fill = guide_legend(title = "Method")) +
    ggtitle("Iterations per Method") +
    theme(
        legend.title = element_text(color = "blue", size = 10),
        plot.title = element_text(
            color = "black",
            size = 30,
            face = "bold",
            hjust = 0.5)
    )

niter_g_plot
```


```{r}
# Execution time per iterations
boxplot_tpi <- data %>%
    ggplot(aes(x =  Method, y = tex/niter, color = Method)) +
    geom_boxplot() +
    scale_y_continuous(trans = "log10") +
    xlab("Algorithm") +
    ylab("Execution time per iteration") +
    guides(fill = guide_legend(title = "Method")) +
    ggtitle("Execution time per iterations") +
    theme(
        legend.title = element_text(color = "blue", size = 10),
        plot.title = element_text(
            color = "black",
            size = 30,
            face = "bold",
            hjust = 0.5)
    )


boxplot_tpi
```

```{r}
# Running time per iteration
tex_niter_jitter_plot <- data %>%
    ggplot(aes(x = num_target, y = tex/niter)) +
    geom_jitter() +
    geom_smooth(se = FALSE) +
    scale_x_continuous(breaks = seq(0, 10, by = 1)) +
    xlab("Target number") +
    ylab("Time of execution (s)") +
    facet_wrap(~Method + factor(la)) +
    ggtitle("Execution time per iteration") +
    theme(
        legend.title = element_text(color = "blue", size = 10),
        plot.title = element_text(
            color = "black",
            size = 30,
            face = "bold",
            hjust = 0.5)
    )


tex_niter_jitter_plot
```


### Discussion

## Performance
### Large Problems
### Accuracy
```{r}
# Training accuracy per Method
tr_acc_g_plot <- data %>%
    ggplot(aes(x = Method, y = tr_acc, color = Method)) +
    geom_boxplot() +
    geom_jitter(shape = 16, position = position_jitter(0.2)) +
    facet_grid(~factor(la)) +
    scale_y_continuous(trans = "log10") +
    xlab("") +
    ylab("Accuracy") +
    facet_grid(~factor(la)) +
    ggtitle("Training Accuracy") +
    theme(
        legend.title = element_text(color = "blue", size = 10),
        plot.title = element_text(
            color = "black",
            size = 30,
            face = "bold",
            hjust = 0.5)
    )


tr_acc_g_plot
```

```{r}
# Test accuracy per Method
te_acc_g_plot <- data %>%
    ggplot(aes(x = Method, y = te_acc, color = Method)) +
    geom_boxplot() +
    geom_jitter(shape = 16, position = position_jitter(0.2)) +
    facet_grid(~factor(la)) +
    scale_y_continuous(trans = "log10") +
    xlab("") +
    ylab("Accuracy") +
    facet_grid(~factor(la)) +
    ggtitle("Test Accuracy") +
    theme(
        legend.title = element_text(color = "blue", size = 10),
        plot.title = element_text(
            color = "black",
            size = 30,
            face = "bold",
            hjust = 0.5)
    )

te_acc_g_plot
```

```{r}
niter_tex_g_plot <- data %>%
    ggplot(aes(x = niter, y = tex)) +
    geom_point() +
    geom_smooth(se = FALSE) +
    scale_x_continuous(trans = "log10") +
    xlab("Number of Iterations") +
    ylab("Time of execution (s)") +
    facet_wrap(~factor(la) + Method) +
    ggtitle("Number of Iterations vs Time of execution") +
    theme(
        legend.title = element_text(color = "blue", size = 10),
        plot.title = element_text(
            color = "black",
            size = 30,
            face = "bold",
            hjust = 0.5)
    )
niter_tex_g_plot
```

```{r}
niter_tex_g_plot <- data %>%
    ggplot(aes(x = num_target, y = tex / niter)) +
    geom_point() +
    geom_smooth(se = FALSE) +
    scale_x_continuous(breaks = seq(0, 10, by = 1)) +
    xlab("Target Number") +
    ylab("") +
    facet_wrap(~factor(la) + Method) +
    ggtitle("tex/niter per target number") +
    theme(
        legend.title = element_text(color = "blue", size = 10),
        plot.title = element_text(
            color = "black",
            size = 30,
            face = "bold",
            hjust = 0.5)
    )
niter_tex_g_plot
```